# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua


$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

bind = $mainMod, Q, killactive
bind = $mainMod, T, exec, $terminal
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, brave --password-store=basic
bind = $mainMod, P, exec, killall waybar; waybar

exec-once = waybar

